### ISSUE TITLE
Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by potibm** [configcat/php-sdk#13]
### Describe the bug

Yesterday I was seeing a spike of the above mentioned warnings in Logs and Sentry for https://github.com/configcat/php-sdk/blob/master/src/ConfigCatClient.php#L313. 

Sorry for the inconcrete bug report. Actually I was not able to reproduce 100% and it might have to do with my setup. 

Looking at the code it might have to do with a corrupted cache. Perhaps you could add some further checks in ConfigCatClient::getConfig?

### To reproduce

- Configcat PHP in current version, configured with PSR6Cache
- Symfony in 5.2.5
- ...dunno?!

### Expected behavior

No warning

**Comment by laliconfigcat** [comment]
Hello,

Yesterday there was a problem with our SSL certificate. You can read more about it at https://status.configcat.com/.
However, we'll investigate this issue, as the error message doesn't seem right.

Cheers,

**Comment by z4kn4fein** [comment]
Hey,
We fixed the error handling and the reported message related to this in [v5.2.1](https://github.com/configcat/php-sdk/releases/tag/v5.2.1)
