### ISSUE TITLE
Downgrade fallback scenarios logging from error to warning

### ISSUE THREAD

**Issue by mente** [configcat/php-sdk#18]
### Is your feature request related to a problem? Please describe.

We use logger extensively and we have different logging logic depending on the level of log message. For errors we consider transaction as completely failed and unrecoverable. It goes hand in hand with [PSR logger levels](https://www.php-fig.org/psr/psr-3/)

>  `error` - Runtime errors that do not require immediate action but should typically be logged and monitored.
> `warning` - Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.

### Describe the solution you'd like

Will it be possible to move the default fallback value fetching from `error` to `warning`?

### Describe alternatives you've considered

Alternatively, we will have to overwrite the logger on our side and downgrade it manually. Customization I prefer to avoid and be fixed in upstream instead.

**Comment by z4kn4fein** [comment]
Hi @mente, thank you for reaching out, and sorry for the late response!
I see the issue here but for the sake of backward compatibility (I'm not sure how many users expecting those entries in their error feed already), I can imagine a configuration option like `log-fallback-errors-as-warnings` that could redirect those error logs to the warning level. What do you think?

**Comment by mente** [comment]
I think it's too insignificant to have the log level configurable (especially between error and warning levels). If you consider keeping backwards compatibility I would rather not do it at all for the sake of simplicity :).

Thanks for the reply.

**Comment by z4kn4fein** [comment]
It might be insignificant in this form, but I wouldn't like to ignore it if it could be helpful for someone :). To give it a bit more significance I thought it could be an option like `log-non-exception-errors-as-warnings` (I'm just not able to come up with short names :D), so with that option enabled, we could redirect every error logs that not coming from exceptions (aka only the logical errors) to `warning`. How does that sound? 
This wouldn't introduce much more complexity as we can handle it on the logger level, and will cover further log entries if we come up with more in the future.

**Comment by mente** [comment]
No, seriously :D. For such hastle I would do something like rewriting the log level internally with anonymous class instead of going into option for each line of code :)

**Comment by mente** [comment]
Here's what we ended up with. It's factory method for the client.

```php
    /**
     * @param array<string, mixed> $options
     */
    public function build(string $sdkKey, LoggerInterface $logger, array $options = []): ConfigCatClient
    {
        $defaultOptions = [
            'cache' => $this->cache,
            'logger' => new class($logger) extends AbstractLogger {
                private LoggerInterface $logger;

                public function __construct(LoggerInterface $logger)
                {
                    $this->logger = $logger;
                }

                public function log($level, $message, array $context = array())
                {
                    if ($level === LogLevel::ERROR) {
                        $level = LogLevel::WARNING;
                    }
                    $this->logger->log($level, $message, $context);
                }
            },
            'data-governance' => DataGovernance::EU_ONLY, // Our Organization is configured to use EU CDN nodes only.
            'cache-refresh-interval' => self::CACHE_REFRESH_INTERVAL,
            'request-options' => [
                RequestOptions::TIMEOUT => 1,
                RequestOptions::CONNECT_TIMEOUT => 0.5,
            ],
        ];

        return new ConfigCatClient(
            $sdkKey,
            array_merge($defaultOptions, $options)
        );
    }
```

**Comment by z4kn4fein** [comment]
Ah, I see, my intention was to avoid redirecting every error to the warning level by separating them into exceptional and logical errors. But if it's acceptable for you then I'll leave the logging for now as is. :)

Thank you for showing how you're using the SDK!
