### ISSUE TITLE
Deprecation regarding LoggerInterface implementation inside InternalLogger (needs return types)

### ISSUE THREAD

**Issue by manonworld** [configcat/php-sdk#20]
### Describe the bug

There are deprecation warnings regarding LoggerInterface implementation inside InternalLogger (and it needs return types) to be defined as void

### To reproduce

1. Configure your Symfony application to have ConfigCat logger enabled
2. Start hitting any endpoint that produces any logs
3. Monitor your console to see these deprecation warnings

### Expected behavior

I think that these deprecations should disappear if we just added return types to methods.

### Screenshots

![screenshot](https://i.ibb.co/YkMyn7c/Screenshot-2022-03-19-at-12-16-17-PM-1-1.jpg)

**Comment by z4kn4fein** [comment]
Hi @manonworld,
With the release v6.0.0 we increased the required minimum PHP version to 7.1 and added the type hints accordingly. Can you verify that the deprecation warnings are no longer shown using the new version? Thanks!

**Comment by manonworld** [comment]
Yes, sure. Appreciated. Works like a dream.

**Comment by z4kn4fein** [comment]
Thanks for the quick response and the report!
