### ISSUE TITLE
Improve testability of implementations using `ConfigCatClient` as a dependency

### ISSUE THREAD

**Issue by tPl0ch** [configcat/php-sdk#22]
### We cannot provide mocks or stubs for `ConfigCatClient`

Since it is `final`, and does not implement any interface, it is impossible to use it as a dependency in unit test environments.

### Only option for now: going full throttle

The only alternative is setting up an integration test config with a separate SDK key and providing feature flags that we could use to validate the behavior. This is unfortunately quite some hassle to go through, especially if you only want to unit test an implementation using the Client as a dependency.

#### Remove the `final` keyword

* Pro: It's easy
* Con: It enables user-space overriding the client and potentially breaking the behavior.

#### Extract an interface from the Client implementation

* Pro: The Client implementation can stay as it is but user-space can use the interface to provide alternative implementations if needed
* Con: Can't really see one to be honest

### Conclusion

I believe you (or us via PR) adding an interface would make life a lot easier when testing user-space applications.

**Comment by z4kn4fein** [comment]
Thank you for the report and PR! I'm going to release a new version with your changes.

**Comment by z4kn4fein** [comment]
It's released in [v6.1.0](https://github.com/configcat/php-sdk/releases/tag/v6.1.0)
