### ISSUE TITLE
Update of monolog version

### ISSUE THREAD

**Issue by mhv666** [configcat/php-sdk#29]
### Is your feature request related to a problem? 
Right now I'm trying to update a Laravel 10, wich requires monolog/monolog ^3.0 and configcat/configcat-client on v6.2.1 requires "monolog/monolog": "^1.6|^2.0"
![image](https://user-images.githubusercontent.com/11708446/223758865-6f5b7d06-32fa-4701-b1f6-c975e2ae9f98.png)
![image](https://user-images.githubusercontent.com/11708446/223759080-375bca22-10d2-45cf-be16-dbc3643b8e2f.png)

### Describe the solution you'd like
Update the monolog version and others dependencies needed

**Comment by z4kn4fein** [comment]
Hi @mhv666, thank you for the report! I'm going to jump into this and I'll notify you when it's ready.

**Update**: I just realized that monolog v3 and laravel 10 bumped their minimum PHP version to `8.1`, which also forces us to increase the PHP version. Let me discuss the upgrade first with the team.

**Comment by z4kn4fein** [comment]
Hey @mhv666, I've released `v7.0.0`, which now targets PHP 8.1. It should be compatible with laravel 10 now. Let me know if you have further issues with the integration.
