### ISSUE TITLE
Configcat using old monolog dependency

### ISSUE THREAD

**Issue by denitsa-md** [configcat/php-sdk#3]
[monolog/monolog ](https://packagist.org/packages/monolog/monolog)has a new 2.0 version but the dependency here is still at 1.6. Any plans on upgrading that?

**Comment by sigewuzhere** [comment]
Hi, @denitsa-cm!

Thanks for the heads up. I'll put the task on my todo list. If you'd like it sooner, I'm happy to receive PRs.

**Comment by configcat** [comment]
Hey, we updated the monolog dependency, it allows ^2.0 now.
