### ISSUE TITLE
Make Guzzle dependency optional

### ISSUE THREAD

**Issue by ruudk** [configcat/php-sdk#38]
It would be great if the Guzzle dependency could be made optional.

Instead, the project should allow any PSR7 client.

One way to deal with this is using https://github.com/php-http/discovery.

This allows people to use their own compatible client.

**Comment by z4kn4fein** [comment]
Hi @ruudk, thank you for the suggestion! I agree it should be replaceable. I'll make it configurable with a configuration option.

However, I'm not sure if we can remove the direct dependency on Guzzle as we'd keep it for a default HTTP client when the user is not configuring anything custom.

**Comment by ruudk** [comment]
Same as with #41, people that use a dependency for something as Configcat, know how to also pull in a Guzzle dependency. 

This SDK is not for hello world projects. I believe it's only used when a project get more serious and has a need for feature flags 😉

**Comment by z4kn4fein** [comment]
Hey @ruudk, in `v8.1.0`, the underlying HTTP client became replaceable. In the next major upgrade we'll move `guzzlehttp/guzzle` into `suggest`.

**Comment by ruudk** [comment]
⚡  Great work!
