### ISSUE TITLE
PHPStan

### ISSUE THREAD

**Issue by ruudk** [configcat/php-sdk#39]
It would be great to setup PHPStan on CI to make sure everything is correct.

https://phpstan.org/

**Comment by z4kn4fein** [comment]
Hi @ruudk, thank you for the suggestion! I'll take a look and configure it for our CI.

**Comment by z4kn4fein** [comment]
Hey @ruudk, `phpstan` along with `php-cs-fixer` is now configured for the CI workflow.

**Comment by ruudk** [comment]
Great, thanks!
