### ISSUE TITLE
Replace `z4kn4fein/php-semver` with `composer/semver`

### ISSUE THREAD

**Issue by ruudk** [configcat/php-sdk#40]
We're investigating if we can use this SDK but we see that it depends on [z4kn4fein/php-semver](https://github.com/z4kn4fein/php-semver).

Looking at the usage, I believe the same can be done with the [composer/semver](https://github.com/composer/semver).

I'd rather see this trustworthy dependency being pulled in than the other one.

**Comment by z4kn4fein** [comment]
Hi @ruudk, thank you for the suggestion! We've checked `composer/semver` but we have a bunch of semantic version related tests that it doesn't satisfy. 

This was the very reason we (I'm the author of `z4kn4fein/php-semver`) created a specific library to satisfy our test set along with the whole [semver spec](https://semver.org).

Is this a blocker for you?

**Comment by ruudk** [comment]
Ah. That's good to know. 

It's just that it looks suspicious seeing an SDK pull in a dependency with only 11 stars. 

Also, what happens when you leave the company.

If it's possible, I would suggest to just embed the code inside this repository.

**Comment by z4kn4fein** [comment]
Hey @ruudk, we discussed this and decided to keep the dependency to `z4kn4fein/php-semver` in the project. We don't consider it suspicious as it's fully open-sourced, and everyone can check what it's doing. 

If I ever leave the company, it won't mean I'll stop supporting my OS projects. Besides, I won't leave anytime soon as I'm one of the founders. :)
