### ISSUE TITLE
Drop dependency on `monolog/monolog`

### ISSUE THREAD

**Issue by ruudk** [configcat/php-sdk#41]
Why does this SDK need `monolog/monolog`? It should just require any `psr/log` logger.

**Comment by z4kn4fein** [comment]
Hi @ruudk, the SDK defaults to `monolog/monolog` when the user doesn't specify a custom logger. It's configurable via the `logger` option which accepts any `psr/log` implementation.

**Comment by ruudk** [comment]
Then why not use [suggest](https://getcomposer.org/doc/04-schema.md#suggest) config option for this?

People that pull in a dependency like this, know how to also pull in a logger.

**Comment by z4kn4fein** [comment]
Hey @ruudk, in `v8.1.0`, the dependency to `monolog/monolog` is dropped.

**Comment by ruudk** [comment]
⚡
