### ISSUE TITLE
php warning when ConfigCatClient class is loaded

### ISSUE THREAD

**Issue by kooliahmd** [configcat/php-sdk#6]
`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/service/vendor/configcat/configcat-client/src/RolloutEvaluator.php on line 235`

**How to reproduce:**
PHP version 7.3.18
When ConfigCatClient class is loaded, a warning is prompt to terminal

**Comment by z4kn4fein** [comment]
Thanks for reporting! We are going to fix this.

**Comment by z4kn4fein** [comment]
I have released a new [version](https://github.com/configcat/php-sdk/releases/tag/v4.0.1), it'll be publicly available soon. 
Could you please confirm that the warning is gone at your side as well? Thanks!

**Comment by kooliahmd** [comment]
@z4kn4fein Problem solved!
Many thanks for your fast intervention.
